name: Test
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout dx-automator
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 8

      - name: Install Dependencies
        run: npm install

      - name: Build & Test
        run: npm run all

      - name: Show git status and fail on diff
        run: |
          git status
          test -z "$(git status --porcelain)"
