name: Test
on:
  pull_request:
    branches: [ main ]

jobs:
  test-actions:
    name: Test Actions
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout dx-automator
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build & Test
        run: npm run all

      - name: Show git status and fail on diff
        run: |
          git status
          git diff
          test -z "$(git status --porcelain)"

  test-examples:
    name: Test Examples
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout dx-automator
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'

      - name: Install Dependencies
        run: make test-install

      - name: Test
        run: make test
